version: '3.1'

services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladbone:mysql
        
    ports:
      - 8080:80
    volumes:
      - "../:/var/www/html"
    environment:
      JOOMLA_DB_HOST: joomladbone
      JOOMLA_DB_PASSWORD: pass1

  joomladbone:
    image: mysql:5.6
    ports:
      - 3306
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: pass1